package cc.xfl12345.mybigdata.server.common.appconst;

public enum TableCurdResult {
    SUCCEED,
    DUPLICATE,
    UNKNOWN_FAILED,
    NO_EXECUTE,
    FAILED_GET_GID_TIMEOUT,
    FAILED_OVER_FLOW,
    FAILED_TYPE_ERROR,
    FAILED_ILLEGAL_DATA,
    FAILED_NOT_FOUND,
    FAILED_COUNTS_NOT_MATCH,
    FAILED_OPERATION_REJECTED
}
